apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: PHP
  generation: 13
  name: php
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run PHP 5 applications with official image.
      iconClass: icon-php
      openshift.io/display-name: PHP 5
      sampleRepo: https://github.com/WordPress/WordPress.git
      supports: php:5,php
      tags: builder,php
      version: "5"
    from:
      kind: DockerImage
      name: docker.io/oondeo/php-5-nginx:latest
    generation: 13
    importPolicy: {}
    name: "5"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run PHP 7.0 applications on CentOS 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/7.0/README.md.
      iconClass: icon-php
      openshift.io/display-name: PHP 7.0
      sampleRepo: https://github.com/WordPress/WordPress.git
      supports: php:7.0,php
      tags: builder,php
      version: "7.0"
    from:
      kind: DockerImage
      name: centos/php-70-centos7:latest
    generation: 9
    importPolicy: {}
    name: "7.0"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run PHP 7.2 applications on CentOS 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/oondeo/docker-php/README.md.
      iconClass: icon-php
      openshift.io/display-name: PHP 7.2
      sampleRepo: https://github.com/WordPress/WordPress.git
      supports: php:7.2,php
      tags: builder,php
      version: "7.2"
    from:
      kind: DockerImage
      name: docker.io/oondeo/php:7.2
    generation: 9
    importPolicy: {}
    name: "7.2"
    referencePolicy:
      type: Source      
  - annotations:
      description: Build and run PHP 7.2 applications on CentOS 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/oondeo/docker-php/README.md.
      iconClass: icon-php
      openshift.io/display-name: PHP 7.2 FPM
      sampleRepo: https://github.com/WordPress/WordPress.git
      supports: php:7.2,php
      tags: builder,php
      version: "7.2-fpm"
    from:
      kind: DockerImage
      name: docker.io/oondeo/php:7.2-fpm
    generation: 9
    importPolicy: {}
    name: "7.2-fpm"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Build and run PHP applications on CentOS 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/5.6/README.md.
        WARNING: By selecting this tag, your application will automatically update to use the latest version of PHP available on OpenShift, including major versions updates.
      iconClass: icon-php
      openshift.io/display-name: PHP (Latest)
      sampleRepo: https://github.com/WordPress/WordPress.git
      supports: php
      tags: builder,php
    from:
      kind: ImageStreamTag
      name: "latest"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
