apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: PHP
    openshift.io/image.dockerRepositoryCheck: 2017-10-30T10:04:08Z
  creationTimestamp: 2017-09-28T17:57:40Z
  generation: 13
  name: php
  namespace: openshift
  resourceVersion: "239446"
  selfLink: /oapi/v1/namespaces/openshift/imagestreams/php
  uid: 853e915a-a476-11e7-b980-6e8cda8356bf
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run PHP 5 applications with official image.
      iconClass: icon-php
      openshift.io/display-name: PHP 5
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:5,php
      tags: builder,php
      version: "5"
    from:
      kind: DockerImage
      name: oondeo/php-5-nginx:latest
    generation: 13
    importPolicy: {}
    name: "5"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run PHP 7.0 applications on CentOS 7. For more information
        about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/7.0/README.md.
      iconClass: icon-php
      openshift.io/display-name: PHP 7.0
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:7.0,php
      tags: builder,php
      version: "7.0"
    from:
      kind: DockerImage
      name: centos/php-70-centos7:latest
    generation: 9
    importPolicy: {}
    name: "7.0"
    referencePolicy:
      type: Source
  - annotations:
      description: |-
        Build and run PHP applications on CentOS 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-php-container/blob/master/5.6/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of PHP available on OpenShift, including major versions updates.
      iconClass: icon-php
      openshift.io/display-name: PHP (Latest)
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php
      tags: builder,php
    from:
      kind: ImageStreamTag
      name: "7.0"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
