apiVersion: v1
kind: Template
labels:
  template: php-mysql-example
message: |-
  The following service(s) have been created in your project: ${NAME}, ${NAME}.

metadata:
  annotations:
    description: |-
      An example PH application with a MySQL database.

      NOTE: The MySQL service created by this template uses non-persistent storage. To setup persisted storage, change this template to use a persistent volume claim instead of emptydir.
    iconClass: icon-php
    openshift.io/display-name: PHP + MySQL (Ephemeral)
    tags: quickstart,instant-app,php,wordpress
  name: php-mysql-example
  namespace: openshift
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    database-password: ${DATABASE_PASSWORD}
    database-root-password: ${DATABASE_ROOT_PASSWORD}
    database-user: ${DATABASE_USER}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/dependencies: '[{"name": "${NAME}",
        "kind": "Service"}]'
    name: ${NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/dependencies: '[{"name": "${NAME}",
        "kind": "Service"}]'
    name: ${NAME}1
  spec:
    ports:
    - name: web1
      port: 8081
      targetPort: 8081
    selector:
      name: ${NAME}      
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: ${NAME}1
  spec:
    host: ${DOMAIN_DEV}
    to:
      kind: Service
      name: ${NAME}1         
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}  
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:5
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8081
            protocol: TCP     
          - containerPort: 9000
            protocol: TCP
          env:
          - name: DOMAIN_PROD
            value: "${APPLICATION_DOMAIN}"   
          - name: DOMAIN_DEV
            value: ${DOMAIN_DEV}
          - name: NGINX_CACHE
            value: ${CACHE}                                            
          - name: PHPINI_OPCACHE__ENABLE
            value: ${CACHE}
          - name: PHPINI_APC__ENABLE
            value: ${CACHE} 
          - name: DEBUG_ENABLE
            value: ${DEBUG}                        
          - name: DATABASE_NAME
            value: ${DATABASE_NAME}
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${NAME}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${NAME}
          image: ' '
          name: php
          args: ["/usr/bin/runsvdir", "/opt/app-root/etc/service"]
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              host: "${APPLICATION_DOMAIN}"
            initialDelaySeconds: 5
            periodSeconds: 10     
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              host: "${APPLICATION_DOMAIN}"              
            initialDelaySeconds: 5
            periodSeconds: 10                   
          resources:
            limits:
              memory: ${MEMORY_LIMIT}          
          volumeMounts:
          - mountPath: /tmp
            name: tmpdir             
        volumes:
        - emptyDir:
            medium: ""
          name: tmpdir          
    triggers: 
    - imageChangeParams:
        automatic: true
        containerNames:
        - php
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the database server
    name: mysql
  spec:
    ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    selector:
      name: mariadb
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the database
    name: mariadb
    labels:
      app: mariadb
  spec:
    replicas: 1
    selector:
      name: mariadb
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: mariadb
        name: mariadb
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${NAME}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${NAME}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: ${NAME}                
          - name: MYSQL_DATABASE
            value: ${DATABASE_NAME}
          image: ' '
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mariadb
          ports:
          - containerPort: 3306
            protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                  -D $MYSQL_DATABASE -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MEMORY_MYSQL_LIMIT}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mariadb
        from:
          kind: ImageStreamTag
          name: 'mariadb:latest'
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
parameters:
- description: Application name
  name: NAME
  value: php-mysql-example
- description: The URL of the repository with your application source code
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/wordpress/wordpress.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository
  name: CONTEXT_DIR
- description: The exposed hostname that will route to the php service, if left
    blank a value will be defaulted.
  name: APPLICATION_DOMAIN
- description: Maximum amount of memory the PHP container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi  
- description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- description: Database name
  name: DATABASE_NAME
  value: phpexample
- description: Database user name
  name: DATABASE_USER
  value: phpexample
- description: Database user password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: DATABASE_PASSWORD
- description: Database root password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: DATABASE_ROOT_PASSWORD  
- description: Maximum amount of memory the MySQL container can use.
  displayName: Memory Limit (MySQL)
  name: MEMORY_MYSQL_LIMIT
  required: true
  value: 512Mi
- description: Activate cache
  name: CACHE
  required: true
  value: "false"
- description: Activate debug
  name: DEBUG
  required: true
  value: "true"  
- description: developer internet domain internet domain, you must create a route for it
  name: DOMAIN_DEV
  required: true
  value: example.127.0.0.1.nip.io